# 基础路径配置
base:
  base_test_url: http://park.test.hhrchina.com
  base_login_url: /account/login
  base_register_url: /account/register
  base_park_information_url: /registerArea/getRegisterArea
  base_park_settlement_url: /settledRequestNote/save
  base_home_investment_products_url: /parkServiceProduct/page?page=1&pageSize=3&token=50aa11de78ee5cb27381df1679f24e15&noCanClose=0&uid=&nickName=&phone=
  base_home_listing_products_url: /propertyManagement/page?page=1&pageSize=3&token=50aa11de78ee5cb27381df1679f24e15&noCanClose=0&uid=&nickName=&phone=
  base_home_park_announcement_url: /areaCompany/getCompanyNewsList?page=1&pageSize=7&search=&type=
  base_product_list_url: /parkServiceProduct/page
  base_product_details_url: /parkServiceProduct/getById
  base_property_list_url: /propertyManagement/page
  base_property_details_url: /propertyManagement/getById
  base_park_announcement_url: /areaCompany/getCompanyNewsList
  base_enterprise_list_url: /areaCompany/getCompanyList
  base_enterprise_details_url: /areaCompany/getCompanyById

# 请求头方式x-www-form-urlencoded
headers-data:
  Content-Type: "application/x-www-form-urlencoded;charset=UTF-8"
  Accept: "application/json, text/plain, */*"
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"

# 请求头方式application/json
headers-json:
  Content-Type: "application/json;charset=UTF-8"
  Accept: "application/json, text/plain, */*"
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"